# Generated by Django 4.1.7 on 2023-03-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('author', models.CharField(max_length=300)),
                ('illustrator', models.CharField(max_length=300)),
                ('country', models.CharField(max_length=300)),
                ('language', models.CharField(max_length=300)),
                ('series', models.CharField(max_length=300)),
                ('genre', models.CharField(max_length=300)),
                ('set_in', models.CharField(max_length=300)),
                ('publisher', models.CharField(max_length=300)),
                ('publication_date', models.DateField()),
                ('pages', models.CharField(max_length=300)),
                ('isbn', models.CharField(max_length=300)),
                ('preceded_by', models.CharField(max_length=300)),
                ('followed_by', models.CharField(max_length=300)),
                ('followed_url', models.URLField(max_length=1000)),
                ('film', models.CharField(max_length=300)),
                ('film_url', models.URLField(max_length=1000)),
            ],
        ),
    ]
