# Generated by Django 4.1.7 on 2023-03-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0002_alter_book_film_alter_book_film_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='release_number',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
