# Generated by Django 4.1.7 on 2023-03-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0003_book_release_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='preceded_url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
