# Generated by Django 4.1.7 on 2023-03-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0004_book_preceded_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='img',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
