# Generated by Django 4.1.7 on 2023-03-18 20:01

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('BookNirvana', '0008_library_shelf'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('shelves', models.JSONField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.DeleteModel(
            name='Library',
        ),
        migrations.RemoveField(
            model_name='shelf',
            name='book_id',
        ),
        migrations.AddField(
            model_name='shelf',
            name='books',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shelf',
            name='id',
            field=models.CharField(max_length=3, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='shelf',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BookNirvana.user'),
            preserve_default=False,
        ),
    ]
