# Generated by Django 4.1.7 on 2023-03-19 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0009_user_delete_library_remove_shelf_book_id_shelf_books_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now=True)),
                ('comment', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[(1, 'like'), (0, 'neutral'), (-1, 'dislike')], max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='likes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='ratings',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='reviews',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shelf',
            name='name',
            field=models.CharField(default='Shelf_!', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='liked_books',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='reviews',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
