# Generated by Django 4.1.7 on 2023-03-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0010_review_book_likes_book_ratings_book_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='status',
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Slightly Bad'), (3, 'Good'), (4, 'Great'), (5, 'Exceptional')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
