# Generated by Django 4.1.7 on 2023-03-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0011_remove_review_status_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_books',
        ),
        migrations.RemoveField(
            model_name='user',
            name='reviews',
        ),
        migrations.AddField(
            model_name='user',
            name='book_info',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(choices=[(1, 'Very Bad'), (2, 'Slightly Bad'), (3, 'Good'), (4, 'Great'), (5, 'Exceptional')]),
        ),
    ]
