# Generated by Django 4.1.7 on 2023-03-20 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0012_remove_user_liked_books_remove_user_reviews_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shelf',
            name='books',
        ),
        migrations.AddField(
            model_name='shelf',
            name='book_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='BookNirvana.book'),
            preserve_default=False,
        ),
    ]
