# Generated by Django 4.1.7 on 2023-03-20 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0014_remove_shelf_book_id_shelf_books'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shelves',
        ),
    ]
