# Generated by Django 4.1.7 on 2023-03-20 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0015_remove_user_shelves'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shelves',
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Shelf',
        ),
    ]
