# Generated by Django 4.1.7 on 2023-03-24 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BookNirvana', '0020_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.FileField(default='static/bg.png', upload_to='static')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BookNirvana.user')),
            ],
        ),
    ]
